name: bottom_bar
description: Bottom bar helps create an optimized bottom navigation bar with beautiful animations
version: 1.2.4
homepage: https://github.com/CoderUni/bottom_bar/


environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter